; PlatformIO Project Configuration File
; Flash as sniffer 1: pio run -e sniffer1 -t upload
; Flash as sniffer 2: pio run -e sniffer2 -t upload
; Flash as coordinator: pio run -e coordinator -t upload

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

[env:sniffer1]
build_flags =
    -DROLE_SNIFFER
    -DNODE_ID=1

[env:sniffer2]
build_flags =
    -DROLE_SNIFFER
    -DNODE_ID=2

[env:coordinator]
build_flags =
    -DROLE_COORDINATOR
    -DNODE_ID=3
lib_deps = knolleary/PubSubClient
