; PlatformIO Project Configuration File
; Flash as sniffer: pio run -e sniffer -t upload
; Flash as coordinator: pio run -e coordinator -t upload

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

[env:sniffer]
build_flags = -DROLE_SNIFFER

[env:coordinator]
build_flags = -DROLE_COORDINATOR
lib_deps = knolleary/PubSubClient
